startingSlotVelocityMS:
  min: 30
  max: 100
finalTickInterval:
  min: 1000
  max: 1500
frictionCoeffecient: 1.25
slots:
  - name: "type"
    options:
      - "deckbuilding"
      - "physical game"
  - name: "theme"
    options:
      - "evolution"
      - "cooking"
  - name: "mechanic"
    options:
      - "asymettry"
      - "battle royale"
      - "synergy"
      - "time limit"
      - "permadeath"
