startingSlotVelocityMS:
  min: 16
  max: 85
finalTickInterval:
  min: 850
  max: 1250
frictionCoeffecient: 1.3
slots:
  - name: "type"
    options:
      - "deckbuilding"
      - "physical game"
  - name: "theme"
    options:
      - "evolution"
      - "cooking"
  - name: "mechanic"
    options:
      - "asymettry"
      - "battle royale"
      - "synergy"
      - "time limit"
      - "permadeath"
