startingSlotVelocityMS:
  min: 16
  max: 85
finalTickInterval:
  min: 850
  max: 1250
frictionCoeffecient: 1.3
slots:
  - name: "game type"
    options:
      - "deckbuilding"
      - "physical"
      - "children's"
      - "roleplaying"
      - "puzzle"
      - "party"
  - name: "theme"
    options:
      - "evolution"
      - "cooking"
      - "manifest destiny"
      - "warfare"
      - "invention"
      - "alchemy"
      - "cosmic horror"
      - "commerce"
      - "geometric"
      - "hegemony"
  - name: "key mechanic"
    options:
      - "asymettry"
      - "battle royale"
      - "synergy"
      - "time limit"
      - "permadeath"
      - "collaboration"
      - "perfect knowledge"
      - "shared resources"
      - "see-through cards"
      - "rule changes"
