startingSlotVelocityMS:
  min: 16
  max: 85
finalTickInterval:
  min: 850
  max: 1250
frictionCoeffecient: 1.3
slots:
  - name: "game type"
    options:
      - "deckbuilding"
      - "dexterity"
      - "children's"
      - "roleplaying"
      - "puzzle"
      - "party"
      - "worker placement"
      - "cooperative"
      - "area control"
      - "social deception"
      - "legacy"
      - "combat"
  - name: "theme"
    options:
      - "evolution"
      - "cooking"
      - "manifest destiny"
      - "warfare"
      - "invention"
      - "alchemy"
      - "cosmic horror"
      - "commerce"
      - "geometric"
      - "hegemony"
      - "food chain"
      - "life-cycle"
      - "fantasy"
      - "steam punk"
      - "personal relationships"
      - "martial arts"
      - "exploration"
      - "racing"
      - "pirates"
      - "trains"
  - name: "key mechanic"
    options:
      - "asymettry"
      - "battle royale"
      - "synergy"
      - "time limit"
      - "permadeath"
      - "collaboration"
      - "perfect knowledge"
      - "shared resources"
      - "see-through cards"
      - "rule changes"
      - "auctions"
      - "betting"
      - "pattern building"
      - "memory"
      - "card drafting"
      - "map exploration"
      - "partnership"
      - "tile placement"
